# Generated by Django 4.0.4 on 2022-05-31 06:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='pdfs', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='recs')),
                ('audio_rate', models.IntegerField(default=125, validators=[django.core.validators.MaxValueValidator(175, 'audio_rate would be maximum 175'), django.core.validators.MinValueValidator(75, 'audio_rate would be minimum 75')])),
                ('volume_level', models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(1.0, 'Volume would be maximum 1.0'), django.core.validators.MinValueValidator(0.1, 'Volume would be minimum 0.1')])),
                ('audio_voice', models.CharField(choices=[('com.apple.speech.synthesis.voice.samantha', 'Male'), ('english_rp+f3', 'Female')], default='english_rp+f3', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
