# Generated by Django 4.0.4 on 2022-06-01 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfaudio',
            name='audio_rate',
            field=models.IntegerField(default=200, validators=[django.core.validators.MaxValueValidator(300, 'audio_rate would be maximum 175'), django.core.validators.MinValueValidator(100, 'audio_rate would be minimum 75')]),
        ),
    ]
