# Generated by Django 4.0.4 on 2022-06-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_pdfaudio_audio_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfaudio',
            name='audio_voice',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=1, max_length=100),
        ),
    ]
