# Generated by Django 4.0.4 on 2022-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_alter_pdfaudio_audio_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfaudio',
            name='audio_voice',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1),
        ),
    ]
