# Generated by Django 4.0.4 on 2022-06-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_alter_pdfaudio_audio_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfaudio',
            name='audio_rate',
        ),
        migrations.RemoveField(
            model_name='pdfaudio',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pdfaudio',
            name='volume_level',
        ),
    ]
