# Generated by Django 4.0.4 on 2022-06-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_remove_pdfaudio_audio_rate_remove_pdfaudio_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfaudio',
            name='audio_voice',
        ),
    ]
