# Generated by Django 4.0.2 on 2022-02-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=150, verbose_name='date_of_birth'),
        ),
    ]
