# Generated by Django 4.0.2 on 2022-02-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=150, null=True, verbose_name='date_of_birth'),
        ),
    ]
